name: Build Instube APK (Native)
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Code-ஐ எடுப்பது
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. ZIP ஃபைலை பிரிப்பது (Unzip)
      # Instube.zip என்ற பெயரில் ஃபைல் இருக்க வேண்டும்
      - name: Unzip Source Code
        run: |
          if [ -f "Instube.zip" ]; then
            unzip "Instube.zip"
            # ஒருவேளை ஜிப் உள்ளே ஃபோல்டர் இருந்தால் அதை வெளியே கொண்டு வர:
            if [ -d "Instube" ]; then mv Instube/* .; fi
          else
            echo "Instube.zip file not found!"
            exit 1
          fi

      # 3. Java Setup (Android-க்கு முக்கியம்)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 4. Manifest ஃபைலை சரி செய்தல் (Inject Permissions)
      # நாம் முன்பு உருவாக்கிய பர்மிஷன் கோடை இங்கே சேர்க்கிறோம்
      - name: Inject AndroidManifest.xml
        run: |
          mkdir -p app/src/main
          cat <<EOF > app/src/main/AndroidManifest.xml
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.instube">
              
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
              <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

              <application
                  android:allowBackup="true"
                  android:label="Instube"
                  android:theme="@style/Theme.AppCompat.Light.NoActionBar"
                  android:requestLegacyExternalStorage="true" 
                  android:usesCleartextTraffic="true">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

      # 5. Layout ஃபைலை சரி செய்தல் (Inject Layout)
      # சிம்பிளான டிசைனை இங்கே உருவாக்குகிறோம்
      - name: Inject activity_main.xml
        run: |
          mkdir -p app/src/main/res/layout
          cat <<EOF > app/src/main/res/layout/activity_main.xml
          <?xml version="1.0" encoding="utf-8"?>
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:orientation="vertical"
              android:gravity="center"
              android:padding="20dp">

              <EditText
                  android:id="@+id/urlInput"
                  android:layout_width="match_parent"
                  android:layout_height="wrap_content"
                  android:hint="Paste Link Here (Insta/YouTube)" />

              <Button
                  android:id="@+id/downloadBtn"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="Download Video"
                  android:layout_marginTop="20dp"/>
          </LinearLayout>
          EOF

      # 6. APK உருவாக்குதல் (Gradle Build)
      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      # 7. APK-ஐ அப்லோட் செய்தல்
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Instube-APK
          path: app/build/outputs/apk/debug/app-debug.apk
          
